<document>  ::= <head> <body>
<head>      ::= "<head>" <title> "</head>"
<title>     ::= "<title>" String "</title>"
<body>      ::= "<body>" { <token> } "</body>
<token>     ::= <tag> | <texttoken>
<tag>       ::= <b> | <br>
<texttoken> ::= "<b>" { <token> } "</br>"
<br>        ::= "<br />"